apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-one
  labels:
    {{- include "azure.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "azure.selectorLabels" . | nindent 4 }}
